{:user {:dependencies [[org.clojure/tools.namespace "0.2.10"]
                       [org.clojure/tools.nrepl "0.2.12"]
                       [potemkin "0.3.13"]
                       [alembic "0.3.2"]
                       [criterium "0.4.3"]]
        :plugins [[cider/cider-nrepl "0.10.0"]
                  [refactor-nrepl "1.1.0"]
                  [lein-cljfmt "0.1.7"]
                  [jonase/eastwood "0.2.1"]
                  [lein-kibit "0.0.8"]
                  [lein-try "0.4.3"]]}}
